services:

  wordpress:
    image: wordpress:6.8.2-php8.1-apache
    container_name: wordpress
    restart: unless-stopped
    expose:
      - 80
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`wp.localhost`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.routers.wordpress.loadbalancer.server.port=80
      - traefik.http.routers.wordpress.tls=true